#cloud-config
hostname: Rancher0
rancher:  
 network:
  dns:
   nameservers:
   - 8.8.8.8
   - 8.8.4.4
  interfaces:
   eth*: 
    dhcp: false
   eth0:
    address: 192.168.68.20/24
    gateway: 192.168.68.1
ssh_authorized_keys:
 - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXjNH4M5bzT+uuKS5AdeqI/BfmBewMQh4BI0rqMEpySM7GUP92HUdyEnEZAA5pogEo7/ymKWPELVruPymX6HFJqgW/Csv510+ov/xU9Vwu+E+LEDZ62QaJH+sN9nl+fYDX5jOFoTXbKad8ccchacv7cZEZbCbTlKhdcvB5CQCqctnjPp4fWqzDMpcL2XiFEjI7r2thY9OeV68JBqDCUD5g62+RMCmoorxy9dUeIa/oOud5m6TGvcg7Tb+ntLQPOywL0kvwL2pd9dKM3exK2FKiWP+9cUpz+fKmiaaajyf1csETjEdSnQWj3Z490nRIGF1xaq/yN2TqMM2Lh/aIIKho2FVsscLC9ssIwKjxvWgxa3bDqtxVVyUIDDUGkom+MG90zODqNyq8V9j/kgQb/95Hg0F4trH/Wwu6gtl2Qyrxa+lGxt2AdBqMiGvBBdghEHO38uD/MDBj4+ROYYUstQXrKCUb/+Lscz+D+CI5fVt9VhGAvZ6M0NBB5xiUVuKOmoprpyN5NU28Z1CEICFaA7vevMkFMOrg3NwLAsOyns5qTL1f6k1Xmy7OYHQimkryo6cqgQYqQxyhc2d/mUvFKyDDJz5ZWwu13ldAy92mkI8DUggH1g6+NqovdYNb49suA8qmfsrdvdeYTlvaBUFf6lNTOJ0DvrbT3CrmnLbZk+xmKQ== jameseadams@hotmail.com
